# Generated by Django 4.2.1 on 2023-05-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion_club', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('trayectoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('numero_camiseta', models.IntegerField()),
                ('actualmente_juega_en', models.CharField(choices=[('U10/U12', 'Minibasket'), ('U13', 'SubTrece'), ('U15', 'Infantil'), ('U17', 'Cadete'), ('U19', 'Juvenil'), ('U21/+', 'Primera')], default='U10/U12', max_length=10)),
            ],
        ),
    ]
